apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: library-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AdhamBasheir/library-devops
    targetRevision: HEAD
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: library-devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
